### ISSUE TITLE
Is it compatible with sigfox?

### ISSUE THREAD

**Issue by xiskoct** [azerimaker/Penguino-STM32WL-LoRa-E5#2]
stm32wl is compatible with sigfox but in Lora e5 module they don't put anything about this in the specs. Do you know if we can use x-cube-sigfox later?

**Comment by azerimaker** [comment]
Nothin stops you from using the sigfox stack with LoRa-E5 module. ST has a dedicated secure element for sigfox applications, maybe adding that might improve the auth process.
