### ISSUE TITLE
Archive of files needed to build it ?

### ISSUE THREAD

**Issue by vincegre** [azerimaker/Penguino-STM32WL-LoRa-E5#6]
Hi

Very interested by your nice design but not sure what files I should send at manufacturer to get it built as it asks for gerber and BOM. May you please let me know files I need and requisite for manufacturer to build the board and do components assembly ?

Thanks

Vincèn

**Comment by azerimaker** [comment]
Hi, thanks for your contact. 

All the files you need are in the [fabrication ](https://github.com/azerimaker/Penguino-STM32WL-LoRa-E5/tree/main/hardware/Penguino-STM32WL-LoRa-E5/fabrication) folder. 

Just zip the gerber folder and submit it alongside the BOM excel file. 

Hope it helps. 

Cheers, 

Orkhan

**Comment by vincegre** [comment]
Hi Orkhan

Thanks for your so fast answer ;) I have succeeded to upload the gerber zip as advised as Seeed Fusion service but the BOM is not in valid format for Seeed website :( I'll check later what's the problem and let you know. Was it used with Seeed Fusion service ? as I see you have listed Seeed SKU for most parts !

Cheers

Vincèn

**Comment by azerimaker** [comment]
My pleasure. 

They have a slightly different BOM template, which I already modified. You can use this file: 

[Penguino-STM32WL-E5-BOM_short_Seeed.xlsx](https://github.com/azerimaker/Penguino-STM32WL-LoRa-E5/files/6035477/Penguino-STM32WL-E5-BOM_short_Seeed.xlsx)

Cheers, 

Orkhan

**Comment by vincegre** [comment]
> They have a slightly different BOM template, which I already modified. You can use this file:
> [Penguino-STM32WL-E5-BOM_short_Seeed.xlsx](https://github.com/azerimaker/Penguino-STM32WL-LoRa-E5/files/6035477/Penguino-STM32WL-E5-BOM_short_Seeed.xlsx)

Thanks a lot for the updated file (perhaps put it aside the original one in repository no ?) and I have been able to submit whole job at Seeed, I'm waiting for answer from them !

Cheers

Vincèn

**Comment by azerimaker** [comment]
>  (perhaps put it aside the original one in repository no ?)

will do so. Thanks. 

Good luck with the production.

**Comment by vincegre** [comment]
> Good luck with the production.

Thanks, will update you when I have received the boards from Seeed ;)
